/*SDM>RDS>Delta>PARTICIPANT_ACCOUNT_AUTO_ENROLLMENT_ELECTION_delta.sql*/
/*SDM>RDS>History>PARTICIPANT_ACCOUNT_AUTO_ENROLLMENT_ELECTION_history.sql*/
WITH PTC_CTE AS
(
  SELECT PTC_DMN_ID, SRC_RK_CD, SRC_PTC_ID_HASH, LOD_SRC_PTC_ID_HASH FROM
  (SELECT PTC_DMN_ID, SRC_RK_CD, SRC_PTC_ID_HASH, LOD_SRC_PTC_ID_HASH, LTS_UPD_TS FROM {{source_context}}.TRDS_PTC_DMN
  {% if delta %}
  UNION ALL
  SELECT PTC_DMN_ID, SRC_RK_CD, SRC_PTC_ID_HASH, LOD_SRC_PTC_ID_HASH, LTS_UPD_TS FROM {{source_hist_context}}.TRDS_PTC_DMN
  {% endif %}
  )
QUALIFY ROW_NUMBER() OVER (PARTITION BY PTC_DMN_ID ORDER BY LTS_UPD_TS DESC) = 1
)
SELECT
	 CASE
		WHEN PTC_MERGE.PTC_DMN_ID IS NULL THEN HASH(:PARM_PRD_ID::STRING, UPPER(PTC.SRC_RK_CD::STRING), SRC_PLN_NU::STRING, PTC.SRC_PTC_ID_HASH::STRING,  'FAKE_ACCOUNT')
		ELSE HASH(:PARM_PRD_ID::STRING, UPPER(PTC.SRC_RK_CD::STRING), SRC.SRC_PLN_NU::STRING, PTC.LOD_SRC_PTC_ID_HASH::STRING, 'FAKE_ACCOUNT')
     END AS PARTICIPANT_ACCOUNT_ID
    ,HASH (:PARM_PRD_ID::STRING, SRC_PLN_NU::STRING, MNY_SRC_CD::STRING ) AS PLAN_SOURCE_ID --hash update
    ,NRL_TYP_DMN_ID AS ENROLLMENT_TYPE_ID --hash update, added NRL_TYP_DMN_ID, earlier it was AUTO_ENROLLMENT_TYPE SDM join
    ,TO_TIMESTAMP(SRC.EFC_DT)    AS EFFECTIVE_FROM_DATE
    ,COALESCE(SRC.EXR_DT, TO_TIMESTAMP_NTZ('9999-12-31 23:59:59.999')) AS EFFECTIVE_THROUGH_DATE
    ,IFF(SRC.CRN_RCR_IN = 1, 'Y', 'N') AS CURRENT_RECORD_INDICATOR
    ,:PARM_PRD_ID  AS PROVIDER_ID
    ,HASH (:PARM_PRD_ID::STRING, SRC_PLN_NU::STRING) AS PLAN_ID
    ,CASE
		WHEN PTC_MERGE.PTC_DMN_ID IS NULL THEN HASH(:PARM_PRD_ID::STRING, UPPER(PTC.SRC_RK_CD::STRING), SRC.SRC_PLN_NU::STRING, PTC.SRC_PTC_ID_HASH::STRING )
		ELSE HASH(:PARM_PRD_ID::STRING, UPPER(PTC.SRC_RK_CD::STRING), SRC.SRC_PLN_NU::STRING, PTC.LOD_SRC_PTC_ID_HASH::STRING )
     END AS PARTICIPANT_ID
    ,4 as PROVIDER_SOURCE_SYSTEM_INSTANCE_ID
    ,SRC.SRC_PLN_NU AS SOURCE_SYSTEM_PLAN_VALUE
    ,SRC.DEL_SRC_RCR_IN AS DELETED_SOURCE_SYSTEM_RECORD_INDICATOR
    ,SRC.MNY_SRC_CD AS MONEY_SOURCE_CODE
    ,SRC.NRL_EVT_PTC_AGE_NU AS ENROLLMENT_EVENT_PARTICIPANT_AGE_NUMBER
    ,SRC.ATO_NRL_ELG_IN AS AUTO_ENROLLMENT_ELIGIBLE_INDICATOR
    ,SRC.ATO_NRL_PTC_IN AS AUTO_ENROLLMENT_PARTICIPATION_INDICATOR
    ,SRC.ATO_NRL_STS_CD AS AUTO_ENROLLMENT_STATUS_CODE
    ,SRC.ATO_NRL_STS_NM AS AUTO_ENROLLMENT_STATUS_LABEL
    ,SRC.ATO_NRL_OPT_OUT_IN AS AUTO_ENROLLMENT_OPT_OUT_INDICATOR
    ,SRC.ATO_NRL_PICK_UP_DT AS AUTO_ENROLLMENT_PICK_UP_DATE
    ,SRC.ATO_NRL_END_OF_GRC_PER_DT AS AUTO_ENROLLMENT_END_OF_GRACE_PERIOD_DATE
    ,SRC.ATO_NRL_END_OF_GRC_IN AS AUTO_ENROLLMENT_END_OF_GRACE_INDICATOR
    ,SRC.ATO_NRL_PLN_DFL_DRL_PC AS AUTO_ENROLLMENT_PLAN_DEFAULT_DEFERRAL_PERCENT
    ,SRC.ATO_NRL_PLN_DFL_DRL_AM AS AUTO_ENROLLMENT_PLAN_DEFAULT_DEFERRAL_AMOUNT
    ,SRC.NEW_ATO_NRL_DRL_PC AS NEW_AUTO_ENROLLMENT_DEFERRAL_PERCENT
    ,SRC.PRI_ATO_NRL_DRL_PC AS PRIOR_AUTO_ENROLLMENT_DEFERRAL_PERCENT
    ,SRC.ATO_NRL_DRL_PC_CHN_IN AS AUTO_ENROLLMENT_DEFERRAL_PERCENT_CHANGE_INDICATOR
    ,SRC.NEW_ATO_NRL_DRL_AM AS NEW_AUTO_ENROLLMENT_DEFERRAL_AMOUNT
    ,SRC.PRI_ATO_NRL_DRL_AM AS PRIOR_AUTO_ENROLLMENT_DEFERRAL_AMOUNT
    ,SRC.ATO_NRL_DRL_AM_CHN_IN AS AUTO_ENROLLMENT_DEFERRAL_AMOUNT_CHANGE_INDICATOR
    ,SRC.ATO_NRL_PC_GT_DFL_IN AS AUTO_ENROLLMENT_PERCENT_GREATER_THAN_DEFAULT_INDICATOR
    ,SRC.ATO_NRL_PC_LT_DFL_IN AS AUTO_ENROLLMENT_PERCENT_LESS_THAN_DEFAULT_INDICATOR
    ,SRC.ATO_NRL_PC_EQL_DFL_IN AS AUTO_ENROLLMENT_PERCENT_EQUAL_DEFAULT_INDICATOR
    ,SRC.ATO_NRL_AM_GT_DFL_IN AS AUTO_ENROLLMENT_AMOUNT_GREATER_THAN_DEFAULT_INDICATOR
    ,SRC.ATO_NRL_AM_LT_DFL_IN AS AUTO_ENROLLMENT_AMOUNT_LESS_THAN_DEFAULT_INDICATOR
    ,SRC.ATO_NRL_AM_EQL_DFL_IN AS AUTO_ENROLLMENT_AMOUNT_EQUAL_DEFAULT_INDICATOR
    ,SRC.ATO_NRL_DFL_ALC_USE_IN AS AUTO_ENROLLMENT_DEFAULT_ALLOCATION_USAGE_INDICATOR
    ,SRC.ATO_NRL_PTC_CHN_IN AS AUTO_ENROLLMENT_PARTICIPATION_CHANGE_INDICATOR
    ,SRC.ATO_NRL_OPT_OUT_CHN_IN AS AUTO_ENROLLMENT_OPT_OUT_CHANGE_INDICATOR
    ,SRC.ATO_NRL_ALC_CHN_IN AS AUTO_ENROLLMENT_ALLOCATION_CHANGE_INDICATOR
    ,SRC.ORG_USR_NM AS RECORD_CREATE_USER_NAME
    ,SRC.ORG_TS AS RECORD_CREATE_DATE_TIME
    ,SRC.ORG_SES_NU AS RECORD_CREATE_SESSION_NUMBER
    ,SRC.LTS_UPD_USR_NM AS UPDATE_USER_NAME
    ,SRC.LTS_UPD_TS AS UPDATE_DATE_TIME
    ,SRC.LTS_UPD_SES_NU AS UPDATE_SESSION_NUMBER
FROM {{source_context}}.TRDS_PTC_ATO_NRL_EVT_FCT SRC
LEFT JOIN PTC_CTE PTC ON SRC.PTC_DMN_ID = PTC.PTC_DMN_ID
{% if delta %}
LEFT JOIN {{target_context}}.HELPER_RDS_PARTICIPANT_MERGE_DELTA PTC_MERGE
{% endif %}
{% if history %}
LEFT JOIN {{target_context}}.HELPER_PARTICIPANT_MERGE_HIST PTC_MERGE
{% endif %}
  ON SRC.PTC_DMN_ID = PTC_MERGE.PTC_DMN_ID
WHERE UPPER(SRC.SRC_RK_CD) = 'OMNI' -- Filter participant_id where provider_source_system_instance_id = 1
{% if delta %}
  AND SRC.ARRIVALTIMESTAMP > :LAST_SUCCESS_EXTRACT_END_TS
  AND SRC.ARRIVALTIMESTAMP <= :NEW_EXTRACT_END_TS
{% endif %}
{% if history %}
  AND EFFECTIVE_FROM_DATE <= $HIST_CUT_OFF_DT
{% endif %}